services:
  - type: web
    name: mecaflow-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: ENVIRONMENT
        value: production
    autoDeploy: true